Replace assembly plugin with shade
Avoid "java.lang.NoClassDefFoundError: org/apache/jena/riot/lang/LangRDFXML" by upgrading jena libraries.
Avoid "org.apache.jena.tdb.TDB.getContext() is null" by using shades plugin
Avoid "java.lang.SecurityException: Invalid signature file digest for Manifest main attributes" by removing signatures with shade